env:
  contexts:
    - name: JuiceShop
      urls:
        - http://localhost:3000

jobs:

  - type: spider
    parameters:
      context: JuiceShop
      user: ""

  - type: passiveScan-wait

  - type: activeScan
    parameters:
      context: JuiceShop
      user: ""

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk
      reportFile: zap-auth-report.html
