name: OWASP ZAP Authenticated POC Scan

on:
  workflow_dispatch:


jobs:

  zap-security-scan:

    runs-on: ubuntu-latest


    steps:


    - name: Checkout Repository
      uses: actions/checkout@v4



    # -----------------------------
    # Start OWASP Juice Shop
    # -----------------------------

    - name: Start Juice Shop Container
      run: |

        docker pull bkimminich/juice-shop


        docker run -d \
          --name juice-shop \
          -p 3000:3000 \
          bkimminich/juice-shop


        echo "Waiting for Juice Shop..."

        sleep 30


        curl http://localhost:3000




    # -----------------------------
    # Setup Node + Playwright
    # -----------------------------

    - name: Setup Node.js
      uses: actions/setup-node@v4

      with:
        node-version: 20



    - name: Install Playwright
      run: |

        npm init -y

        npm install playwright

        npx playwright install chromium




    # -----------------------------
    # Authenticate Application
    # -----------------------------

    - name: Login using Playwright
      env:

        APP_USERNAME: ${{ secrets.APP_USERNAME }}

        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

      run: |

        node playwright/login.js




    # Check Auth File

    - name: Verify Authentication File
      run: |

        ls -la

        cat auth.json




    # -----------------------------
    # Start OWASP ZAP
    # -----------------------------

    - name: Start OWASP ZAP Container
      run: |


        docker pull ghcr.io/zaproxy/zaproxy:stable



        docker run -d \
          --name zap \
          --network host \
          -v ${{ github.workspace }}:/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable \
          zap.sh \
          -daemon \
          -host 0.0.0.0 \
          -port 8080 \
          -config api.disablekey=true



        echo "Waiting for ZAP..."

        sleep 30



    # -----------------------------
    # Run ZAP Scan
    # -----------------------------

    - name="Run OWASP ZAP Scan"
      run: |


        docker exec zap \
        zap-full-scan.py \
        -t http://localhost:3000 \
        -r /zap/wrk/zap-report.html \
        -I



    # -----------------------------
    # Upload Report
    # -----------------------------

    - name: Upload ZAP HTML Report

      uses: actions/upload-artifact@v4

      with:

        name: zap-authenticated-report

        path: zap-report.html
