name: OWASP ZAP Authenticated Scan

on:
  workflow_dispatch:

jobs:
  zap-authenticated-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      #################################################
      # Start Juice Shop
      #################################################

      - name: Start Juice Shop
        run: |
          docker run -d \
            --name juice-shop \
            -p 3000:3000 \
            bkimminich/juice-shop

          echo "Waiting for Juice Shop..."

          until curl -s http://localhost:3000 > /dev/null
          do
            sleep 5
          done

          echo "Juice Shop is running."

      #################################################
      # Start ZAP
      #################################################

      - name: Start ZAP
        run: |
          docker run -d \
            --name zap \
            --network host \
            -v ${{ github.workspace }}:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh \
            -daemon \
            -host 0.0.0.0 \
            -port 8080 \
            -config api.disablekey=true

      - name: Wait for ZAP
        run: |
          echo "Waiting for ZAP..."

          until curl -s http://localhost:8080 > /dev/null
          do
            sleep 5
          done

      #################################################
      # Install Node
      #################################################

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      #################################################
      # Install Playwright
      #################################################

      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright
          npx playwright install chromium

      #################################################
      # Login
      #################################################

      - name: Login through ZAP
        env:
          APP_USERNAME: ${{ secrets.APP_USERNAME }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          node playwright/login.js

      #################################################
      # Run Automation Framework
      #################################################

      - name: Run ZAP Automation
        run: |
          docker exec zap \
          zap.sh \
          -cmd \
          -autorun /zap/wrk/zap.yaml

      #################################################
      # Upload Report
      #################################################

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-auth-report.html
